### ISSUE TITLE
[linux_serial] Error when opening serial port

### ISSUE THREAD

**Issue by hareendranmg** [ardera/flutter_packages#18]
When i open serial port, i get the following error.

flutter: NoSuchMethodError: Class 'Array<UnsignedChar>' has no instance method '[]='.
Receiver: Instance of 'Array<UnsignedChar>'
Tried calling: []=(6, 1)

Code:
final ports = SerialPorts.ports;
final port = ports.singleWhere((p) => p.name.contains('ttyUSB'));
final handle = port.open(baudrate: Baudrate.b19200);

The exception occures when open function called.

**Comment by ardera** [comment]
Sorry for the delayed response. I can't reproduce the problem. What flutter version are you using?

**Comment by hareendranmg** [comment]
Hi @ardera,

The issue has been resolved, although I've forgotten the specific solution. By the way, thanks for this package.
