### ISSUE TITLE
[proposal] consider using melos

### ISSUE THREAD

**Issue by iapicca** [ardera/flutter_packages#2]
hi, I noticed that you choose the mono-repo approach
I just wanted to say that relatively recently I've adopted [melos](https://pub.dev/packages/melos) 
and seems to help to keeps things tidy 
(I'm **_not_** associated with melos devs or invertase in any way)

if you want to give it a shot feel free to copy-paste from [my set up](https://github.com/iapicca/yak_packages)
go ahead and close the issue once you read it

**Comment by ardera** [comment]
Oh thats cool thanks!

**Comment by ardera** [comment]
took a while, but it's implemented now. Thanks for the suggestion!
