### ISSUE TITLE
[linux_can] Would it be possible to add CAN FD support to linux_can ?

### ISSUE THREAD

**Issue by RadkMcku** [ardera/flutter_packages#24]
Hi, 

first of all, great work on your repositories, I have checked out and played with the linux_can and it looks very good, I plan to use that together with the flutter-pi. Thanks for all that great work.

I am noob programmer, so can't do it myself really, unless there is someone willing to provide some guidance.

**Comment by ardera** [comment]
Yep, sure. I actually thought about adding it myself, but I wasn't sure if anyone needed it. So it's good that you created an issue :smile:

**Comment by RadkMcku** [comment]
Great, any idea you might get to this? I can help with testing & coding ...

**Comment by ardera** [comment]
@RadkMcku Can't really provide a time-frame, could be next week but could also be only in 2 months unfortunately :/

The testing would really help though, I don't have a CAN FD transceiver at home so I can't really test myself.
