### ISSUE TITLE
iterable<int> is not a subtype of List<int> in writeBytes

### ISSUE THREAD

**Issue by thomasconduction** [ardera/flutter_packages#26]
Im not good at github lol but I have a bug and a fix for it. 
Line 852 in linux_serial.dart:
`bytes = bytes.skip(_bufferSize) as List<int>;`

needs to be 

`bytes = bytes.skip(_bufferSize).toList();`

Sorry I dont know how to make a pull request.

**Comment by thomasconduction** [comment]
as List<int> should be doing a runtime type conversion but the line throws an error unless the `toList()` method is used

**Comment by ardera** [comment]
thanks! fixed in 9d130049eae614ecc62aabae95fcdfdd4266c7c3 (version `0.2.3+6`)
