### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by suyulin** [ardera/flutter_packages#3]
hi,
omxplayer is not support arm64 , What's the solution for arm64?

**Comment by ardera** [comment]
For arm64 there's no solution right now I'm afraid. In the future, I'll create a new plugin which uses OpenGL textures for video playback and not omxplayer, that will work on arm64 too.

**Comment by ardera** [comment]
See [ardera/flutter-pi/gstreamer-video-player](https://github.com/ardera/flutter-pi/tree/feature/gstreamer-video-player).
That's a flutter-pi-only solution though. Currently, video playback and pausing / playback works, but some other things are not yet implemented
