### ISSUE TITLE
example

### ISSUE THREAD

**Issue by pheromone** [ardera/flutter_packages#6]
example？

**Comment by ardera** [comment]
what package do you need an example for? each package has an example bundled with it in the `example` folder.

**Comment by pheromone** [comment]
omxplayer_video_player example，thank you,I use electron + react instead

**Comment by ardera** [comment]
just for completeness:
`omxplayer_video_player` is just a backend for the official [video_player](https://pub.dev/packages/video_player) package. So you set it up like in the readme, and then you just use the `VideoPlayer` widget of the `video_player` package. The examples are [here](https://pub.dev/packages/video_player/example), basically.

That's what I meant with `A package that implements video_player_platform_interface using ...`. But I guess I can make it clearer a bit.

**Comment by ardera** [comment]
clarified it in the readme, not published to pub.dev yet though
